/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_readlog_NDKUtils */

#ifndef _Included_com_jack_readlog_NDKUtils
#define _Included_com_jack_readlog_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_readlog_NDKUtils
 * Method:    exeute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_readlog_NDKUtils_execute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
